name: e-wallet-deploy
services:
  nginx:
    image: nginx:alpine
    container_name: e-wallet-nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
    networks:
      - ewallet_network
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"

  db:
    container_name: e-wallet-db
    image: postgres:14.6-alpine
    restart: always
    environment:
      POSTGRES_DB: ${db_name}
      POSTGRES_USER: ${db_username}
      POSTGRES_PASSWORD: ${db_password}
    volumes:
      - ewallet_postgres_data:/var/lib/postgresql/data
    networks:
      - ewallet_network
    expose:
      - 5432
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"

  frontend:
    container_name: e-wallet-frontend
    image: rida999/e-wallet-frontend:latest
    restart: always
    environment:
      HOST: 0.0.0.0
      REACT_APP_API_BASE_URL: http://backend:8080/api/v1
    depends_on:
      - backend
    networks:
      - ewallet_network
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"

  backend:
    container_name: e-wallet-backend
    image: rida999/e-wallet-backend:latest
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${db_name}
      SPRING_DATASOURCE_USERNAME: ${db_username}
      SPRING_DATASOURCE_PASSWORD: ${db_password}
      SPRING_PROFILES_ACTIVE: prod
      JWT_SECRET: ${jwt_secret}
      JWT_EXPIRATION_MS: 3600000
    depends_on:
      - db
    networks:
      - ewallet_network
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"

volumes:
  ewallet_postgres_data:
    driver: local

networks:
  ewallet_network:
    driver: bridge
